use AB_COBRANCA

--select * from TITULOS t where t.NUMOPERACAO = '1387696' and t.DATACADASTRAMENTO between '2020-01-06' and '2020-01-10'

DECLARE
	@P_CODCOLIGADA VARCHAR(03) = '001',
	@P_CODCLIENTE   VARCHAR(09) = '000400912',
	@P_CODAGENCIA   VARCHAR(05) = '00019',
	@P_CODPRODUTO   VARCHAR(10) = 'CB SIMPLES',
	@P_NUMOPERACAO  VARCHAR(07) = '1387696',--0960962, 1387696
	@P_DATAINICIO   DATETIME	= '2020-01-06',
	@P_DATAFIM      DATETIME	= '2020-01-10', 
	@P_CODUSUARIO   VARCHAR(35),
	@P_SQLERRO      INTEGER,
	@P_MENSERRO     VARCHAR(200)

	

SET NOCOUNT ON  					/* 21/07/2010 */
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED 	/* 21/07/2010 */

DECLARE @DATAPOSICAO 	DATETIME,     	@NOMECLIENTE 	VARCHAR (35),
	  @AGENCIA_EM_USO VARCHAR (05), 	@USUARIO_EM_USO 	VARCHAR (35),
	  @DATA_EM_USO    DATETIME,  		@EMISSAO_LIBERADA VARCHAR (03),
	  @ENDERECO       VARCHAR (40),     @CIDADE           VARCHAR (25),
        @CEP            VARCHAR (08),     @UF               VARCHAR (02),
        @BAIRRO         VARCHAR (20),     @COMPLEMENTO      VARCHAR (10),
        @CGC_CPF        VARCHAR (15),     @SEQUENCIA        VARCHAR (01),
         @CODNOSSOBANCO  VARCHAR (04),
		 @QTDE_DIAS     SMALLINT

SELECT @DATAPOSICAO = DATAPROCESSAMENTO FROM COLIGADAS 
                        WHERE COLIGADAS.CODCOLIGADA = @P_CODCOLIGADA
SELECT @P_SQLERRO = 0, @P_MENSERRO = '' 

SELECT @CODNOSSOBANCO  = PARAMETROS.CODBANCO FROM PARAMETROS /* 24/01/2012 */


/*26/07/2019*/
SELECT @QTDE_DIAS = QTDE_DIAS FROM PARAM_PERIODORELATORIOS WHERE CODRELATORIO = 'FRANCESA_OPERACAO'
IF @QTDE_DIAS IS NULL
BEGIN
	SET @QTDE_DIAS = 0
END

IF @QTDE_DIAS > 0
BEGIN
	IF DATEDIFF(DD, @P_DATAINICIO, @P_DATAFIM) > @QTDE_DIAS
	BEGIN
		SELECT @P_MENSERRO = 'QUANTIDADE DE DIAS ENTRE A DATA DE INICIO E FINAL MAIOR QUE O PERMITIDO ('+CONVERT(VARCHAR(5), @QTDE_DIAS)+' DIAS)'
		GOTO TRATAERRO
	END
END
/*26/07/2019 (FIM)*/

/*------------------------------------------------------*/
/* 06/05/2010 - Criação da temporária */
/*------------------------------------------------------*/
SELECT 
CONVERT(VARCHAR(5),SPACE(1)) CODAGENCIA,
CONVERT(VARCHAR(9),SPACE(1)) CODCLIENTE,
CONVERT(DATETIME,SPACE(01)) DATACADASTRAMENTO,
CONVERT(VARCHAR(42),SPACE(1)) CHAVE,
CONVERT(VARCHAR(35),SPACE(1)) CODUSUARIOMANUTENCAO,
CONVERT(DATETIME,SPACE(1)) DATAMANUTENCAO 
INTO #TEMP_FRANCESA
FROM COLIGADAS
WHERE CODCOLIGADA = '000'

IF @P_CODCLIENTE <> '000000000'
/* cliente informado */
   BEGIN
      SELECT @NOMECLIENTE = NOME, @CGC_CPF = CGC_CPF, @SEQUENCIA = SEQUENCIA
		 FROM INFO_CLIENTES
                      WHERE INFO_CLIENTES.CODCLIENTE = @P_CODCLIENTE
      SELECT @NOMECLIENTE = 
		 ISNULL (@NOMECLIENTE, @P_CODCLIENTE + ' CLIENTE NAO CADASTRADO NO INFOBANK'),
             @ENDERECO = NULL, @BAIRRO = NULL,  @COMPLEMENTO = NULL, @CIDADE = NULL,
             @UF = NULL, @CEP = NULL

      SELECT @ENDERECO = ENDERECO, @CIDADE = CIDADE, @COMPLEMENTO = COMPLEMENTO,
		 @BAIRRO   = BAIRRO,   @CEP = CEP,       @UF = UF
		 FROM INFO_CLIENTE_ENDERECOS
                      WHERE INFO_CLIENTE_ENDERECOS.CGC_CPF 	= @CGC_CPF AND
				    INFO_CLIENTE_ENDERECOS.SEQUENCIA 	= @SEQUENCIA

	IF @P_CODAGENCIA <> '00000'
/* cliente informado / agencia informada */
	   BEGIN
		IF @P_CODPRODUTO <> '##########' 
/* cliente informado / agencia informada / produto informado */
		   BEGIN
			IF @P_NUMOPERACAO <> '0000000'
/* cliente informado / agencia informada / produto informado / operacao informada */
			   BEGIN
/* movimentacao geral */

SELECT 
	upper(X.NOMESACADO) as 'Nome Sacador',
	X.CODHISTORICO as 'Historico',
	X.NOSSONUMERO as 'Nosso Numero',
	X.SEUNUMERO as 'Seu Numero',
	X.DATACADASTRAMENTO as cadastro,
	X.DATAVENCIMENTO as 'Vencimento',
	X.DATAREFERENCIA as 'Referência',
	X.DATACONTABILLANCAR as 'Lançado',
	X.VLRTITULO as 'Valor do Título',
	X.VLRABATIMENTO as 'Abatimento',
	X.VLRDESCONTOS as 'Desconto',
	X.VLRENCARGOS as 'Encargos',
	X.VLRIOF as 'IOF',
	X.VLRTARIFA as 'Tarifa',
	X.VLRLANCARCONTA as 'Líquido'

FROM(

				SELECT 
				EVENTOS_TITULOS.CODAGENCIA,
				@NOMECLIENTE NOMECLIENTE,
				TITULOS.DATACADASTRAMENTO,
				PRODUTOS.NOME NOMEPRODUTO,  
				EVENTOS_TITULOS.NUMOPERACAO,
				1 TIPOREGISTRO  /* Detalhe */, 
				TITULOS.SEUNUMERO,
			 	SUBSTRING (TITULOS.NOME,1,20) NOMESACADO,
				(EVENTOS_TITULOS.NUMCARTEIRA + '/' + EVENTOS_TITULOS.NOSSONUMERO) NOSSONUMERO,
				EVENTOS_TITULOS.CODEVENTO,
				EVENTOS_TITULOS.SEQEVENTO,
				EVENTOS_TITULOS.CODBAIXA,
				EVENTOS.CLASSEEVENTO,
				EVENTOS.TIPOMOVTOSALDO,
				EVENTOS.TIPOMOVTOQTDE,
				TITULOS.DATAVENCIMENTO,
				EVENTOS_TITULOS.DATAREFERENCIA,
				EVENTOS_TITULOS.DATACONTABILLANCAR,
				EVENTOS_TITULOS.VLRREGCONTABIL VLRTITULO,
			      VLRDESCONTOS = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMDESCONTOS
						     ELSE (EVENTOS_TITULOS.VLRMDESCONTOS * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRABATIMENTO = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMABATIMENTO
						     ELSE (EVENTOS_TITULOS.VLRMABATIMENTO * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRENCARGOS   = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMENCARGOS  
						     ELSE (EVENTOS_TITULOS.VLRMENCARGOS * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRMORA       = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMMORA      
						     ELSE (EVENTOS_TITULOS.VLRMMORA * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRMULTA      = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMMULTA     
						     ELSE (EVENTOS_TITULOS.VLRMMULTA * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
				EVENTOS_TITULOS.VLRATUMONETARIA,
				EVENTOS_TITULOS.VLRIOF,
				EVENTOS_TITULOS.VLRTARIFA,
				EVENTOS_TITULOS.VLRLANCARCONTA,
				0 QTDEMCOBRANCA,
				0 VLREMCOBRANCA,
				EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
				0 VLRTOTDEBITO, 0 VLRTOTCREDITO, 
				@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
				@CIDADE CIDADE , @UF UF, @CEP CEP, PRODUTOS.CODPRODUTOCTB, 
				PRODUTOS.CODESPECIECB,
				CASE  WHEN EVENTOS.CLASSEEVENTO IN ('BAIXA', 'LIQUIDACAO')  
					THEN EVENTOS_TITULOS.CODBAIXA  
				   WHEN EVENTOS.CODEVENTO = '0124'  
					THEN EVENTOS_TITULOS.CODBAIXA  
				   ELSE EVENTOS.CODEVENTO  
				  END CODHISTORICO,
				@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
				EVENTOS.NOME NOMEEVENTO, /* 02/07/2018 - Fernanda */
				TIPOS_DE_BAIXA.NOME NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
		FROM  EVENTOS_TITULOS
		/*03/07/2018 - Fernanda*/
			JOIN TITULOS ON EVENTOS_TITULOS.CODCOLIGADA = TITULOS.CODCOLIGADA   
				AND EVENTOS_TITULOS.CODAGENCIA =  TITULOS.CODAGENCIA     
				AND EVENTOS_TITULOS.NUMCARTEIRA = TITULOS.NUMCARTEIRA    
				AND EVENTOS_TITULOS.NOSSONUMERO = TITULOS.NOSSONUMERO
			JOIN OPERACOES ON OPERACOES.CODCOLIGADA = EVENTOS_TITULOS.CODCOLIGADA 
				AND OPERACOES.CODAGENCIA = EVENTOS_TITULOS.CODAGENCIA
				AND OPERACOES.NUMOPERACAO = EVENTOS_TITULOS.NUMOPERACAO
			JOIN PRODUTOS ON PRODUTOS.CODPRODUTO = OPERACOES.CODPRODUTO
			JOIN EVENTOS ON EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO
			LEFT OUTER JOIN TIPOS_DE_BAIXA ON EVENTOS_TITULOS.CODBAIXA = TIPOS_DE_BAIXA.CODBAIXA
			LEFT OUTER JOIN INFO_INDICES ON TITULOS.CODINDICE = INFO_INDICES.CODINDICE AND
				INFO_INDICES.DATAVIGENCIA   = @DATAPOSICAO			

		WHERE 
			TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
			TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
			EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
			EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
			EVENTOS_TITULOS.NUMOPERACAO = @P_NUMOPERACAO         AND
			--EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
			--EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
			--EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
			--OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO    AND	
			--EVENTOS_TITULOS.CODCOLIGADA = TITULOS.CODCOLIGADA    AND
			--EVENTOS_TITULOS.CODAGENCIA =  TITULOS.CODAGENCIA     AND
			--EVENTOS_TITULOS.NUMCARTEIRA = TITULOS.NUMCARTEIRA    AND
			--EVENTOS_TITULOS.NOSSONUMERO = TITULOS.NOSSONUMERO    AND
			--EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
			EVENTOS.GERAEXTRATO 	    = 'SIM'
	     /*03/07/2018 - Fernanda*/
UNION
/* Saldo da operacao movimentada na data */
		SELECT 
			EVENTOS_TITULOS.CODAGENCIA,
			@NOMECLIENTE NOMECLIENTE,
			EVENTOS_TITULOS.DATACADASTRAMENTO,
			PRODUTOS.NOME NOMEPRODUTO,  
			EVENTOS_TITULOS.NUMOPERACAO,
			3 TIPOREGISTRO /* Saldo da operacao */, 
			NULL SEUNUMERO,
		 	NULL NOMESACADO,
			NULL NOSSONUMERO,
			NULL CODEVENTO,
			NULL SEQEVENTO,
			NULL CODBAIXA,
			NULL CLASSEEVENTO,
			NULL TIPOMOVTOSALDO,
			NULL TIPOMOVTOQTDE,
			NULL DATAVENCIMENTO,
			NULL DATAREFERENCIA,
			NULL DATACONTABILLANCAR,
			0 VLRTITULO,
		      0 VLRDESCONTOS,
		      0 VLRABATIMENTO,
		      0 VLRENCARGOS,
		      0 VLRMORA,
		      0 VLRMULTA,
			0 VLRATUMONETARIA,
			0 VLRIOF,
			0 VLRTARIFA,
			0 VLRLANCARCONTA,
                  SALDOS.QTDEMCOBRANCA, SALDOS.VLREMCOBRANCA,
			NULL CODAGENCIALANCAR, NULL NUMCONTALANCAR, 
			0 VLRTOTDEBITO, 0 VLRTOTCREDITO,
			@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
			@CIDADE CIDADE , @UF UF, @CEP CEP, PRODUTOS.CODPRODUTOCTB, 
		      NULL CODESPECIECB,
			  NULL CODHISTORICO,
		      @CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
		    NULL NOMEEVENTO, /* 02/07/2018 - Fernanda */
			NULL NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
	FROM  EVENTOS_TITULOS INNER JOIN OPERACOES ON
		EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
		EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
		EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  	
	      LEFT OUTER JOIN SALDOS ON
	 	OPERACOES.CODCOLIGADA      		= SALDOS.CODCOLIGADA     AND
		OPERACOES.CODAGENCIA       		= SALDOS.CODAGENCIA      AND
		OPERACOES.NUMOPERACAO      		= SALDOS.NUMOPERACAO     AND
	      EVENTOS_TITULOS.DATACADASTRAMENTO 	= SALDOS.DATACADASTRAMENTO 	
	      ,EVENTOS, PRODUTOS
	WHERE 
		EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
		EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
		EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
		EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
		EVENTOS_TITULOS.NUMOPERACAO = @P_NUMOPERACAO         AND

		OPERACOES.CODPRODUTO	    = PRODUTOS.CODPRODUTO    AND
		EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
		EVENTOS.GERAEXTRATO 	    = 'SIM' 		     

      GROUP BY EVENTOS_TITULOS.CODAGENCIA, EVENTOS_TITULOS.DATACADASTRAMENTO,PRODUTOS.NOME,
		   EVENTOS_TITULOS.NUMOPERACAO,	SALDOS.QTDEMCOBRANCA,SALDOS.VLREMCOBRANCA,
               PRODUTOS.CODPRODUTOCTB
UNION
/* resumo em conta */
			SELECT 
			EVENTOS_TITULOS.CODAGENCIA,@NOMECLIENTE NOMECLIENTE,
			EVENTOS_TITULOS.DATACADASTRAMENTO, PRODUTOS.NOME NOMEPRODUTO, 
			@P_NUMOPERACAO NUMOPERACAO,	2 TIPOREGISTRO,
			NULL SEUNUMERO,NULL NOMESACADO,NULL NOSSONUMERO,
			NULL CODEVENTO,NULL SEQEVENTO,NULL CODBAIXA,NULL CLASSEEVENTO,
			NULL TIPOMOVTOSALDO,NULL TIPOMOVTOQTDE,NULL DATAVENCIMENTO,
			NULL DATAREFERENCIA,EVENTOS_TITULOS.DATACONTABILLANCAR,0 VLRTITULO,
			0 VLRDESCONTOS,0 VLRABATIMENTO,0 VLRENCARGOS,0 VLRMORA,0 VLRMULTA,
			0 VLRATUMONETARIA,0 VLRIOF,0 VLRTARIFA,0 VLRLANCARCONTA,
			0 QTDEMCOBRANCA, 0 VLREMCOBRANCA,
			EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
                 	SUM (CASE  WHEN EVENTOS_TITULOS.VLRLANCARCONTA <= 0
				     THEN EVENTOS_TITULOS.VLRLANCARCONTA
				     ELSE 0
                       END) VLRTOTDEBITO, 
                 	SUM (CASE  WHEN EVENTOS_TITULOS.VLRLANCARCONTA >= 0
				     THEN EVENTOS_TITULOS.VLRLANCARCONTA
				     ELSE 0
                       END) VLRTOTCREDITO,
			@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
			@CIDADE CIDADE , @UF UF, @CEP CEP, PRODUTOS.CODPRODUTOCTB,  NULL CODESPECIECB, NULL CODHISTORICO,
			@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
			NULL NOMEEVENTO, /* 02/07/2018 - Fernanda */
			NULL NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
		FROM  EVENTOS_TITULOS, EVENTOS, OPERACOES, PRODUTOS
		WHERE 
			EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
			EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
			EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
			EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
			EVENTOS_TITULOS.NUMOPERACAO = @P_NUMOPERACAO         AND
			EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
			EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
			EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
			OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO    AND
			EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
			EVENTOS.GERAEXTRATO 	    = 'SIM' 		     

		GROUP BY EVENTOS_TITULOS.CODAGENCIA,
			   EVENTOS_TITULOS.DATACADASTRAMENTO, 
			   PRODUTOS.NOME,
			   EVENTOS_TITULOS.CODAGENCIALANCAR, 
			   EVENTOS_TITULOS.NUMCONTALANCAR, 
			   EVENTOS_TITULOS.DATACONTABILLANCAR, 
			   PRODUTOS.CODPRODUTOCTB

		--ORDER BY TITULOS.DATACADASTRAMENTO,TIPOREGISTRO,TITULOS.SEUNUMERO
		) X 
		--WHERE X.NOSSONUMERO in ('112/00121448171','112/00121448254','112/00121722468')
		ORDER BY X.NUMOPERACAO, X.DATACADASTRAMENTO 
			   END
			ELSE
			   BEGIN
/* cliente informado / agencia informada / produto informado / operacao nao informada */
/* Alimentar a tabela auxiliar com a maior operacao movimentada do cliente em cada dia ...*/
			   

			      BEGIN   /* emissao liberada */
			        
			        INSERT INTO #TEMP_FRANCESA
				  (CODAGENCIA, CODCLIENTE, DATACADASTRAMENTO, CHAVE,  /* Eliane - 23/03/2005 */
                		   CODUSUARIOMANUTENCAO, DATAMANUTENCAO)	      /* Eliane - 23/03/2005 */
			          SELECT @P_CODAGENCIA, @P_CODCLIENTE, EVENTOS_TITULOS.DATACADASTRAMENTO,
                                         MAX((PRODUTOS.NOME + REPLICATE ( ' ', (35 - DATALENGTH (PRODUTOS.NOME))) ) + EVENTOS_TITULOS.NUMOPERACAO), /* 26/10/2010 */
			                 @P_CODUSUARIO, GETDATE ()
			          FROM EVENTOS_TITULOS, OPERACOES, PRODUTOS, EVENTOS
			          WHERE
					EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
					EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
					EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
					EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
					EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
					EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
					EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
					OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO    AND	
					OPERACOES.CODPRODUTO        = @P_CODPRODUTO          AND	
					OPERACOES.CODCLIENTE        = @P_CODCLIENTE          AND			
					EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
					EVENTOS.GERAEXTRATO 	    = 'SIM' 		     		
			    
			    GROUP BY EVENTOS_TITULOS.DATACADASTRAMENTO
/* Movimentacao geral ...*/	  
			    SELECT 
				EVENTOS_TITULOS.CODAGENCIA,
				@NOMECLIENTE NOMECLIENTE,
				EVENTOS_TITULOS.DATACADASTRAMENTO,
				PRODUTOS.NOME NOMEPRODUTO,  
				EVENTOS_TITULOS.NUMOPERACAO NUMOPERACAO,	/* 26/10/2010 */
				1 TIPOREGISTRO /* Detalhe */, 
				TITULOS.SEUNUMERO,
			 	SUBSTRING (TITULOS.NOME,1,20) NOMESACADO,
				(EVENTOS_TITULOS.NUMCARTEIRA + '/' + EVENTOS_TITULOS.NOSSONUMERO) NOSSONUMERO,
				EVENTOS_TITULOS.CODEVENTO,
				EVENTOS_TITULOS.SEQEVENTO,
				EVENTOS_TITULOS.CODBAIXA,
				EVENTOS.CLASSEEVENTO,
				EVENTOS.TIPOMOVTOSALDO,
				EVENTOS.TIPOMOVTOQTDE,
				EVENTOS_TITULOS.DATAVENCIMENTO,
				EVENTOS_TITULOS.DATAREFERENCIA,
				EVENTOS_TITULOS.DATACONTABILLANCAR,
				EVENTOS_TITULOS.VLRREGCONTABIL VLRTITULO,
			      VLRDESCONTOS = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMDESCONTOS
						     ELSE (EVENTOS_TITULOS.VLRMDESCONTOS * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRABATIMENTO = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMABATIMENTO
						     ELSE (EVENTOS_TITULOS.VLRMABATIMENTO * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRENCARGOS   = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMENCARGOS  
						     ELSE (EVENTOS_TITULOS.VLRMENCARGOS * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRMORA       = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMMORA      
						     ELSE (EVENTOS_TITULOS.VLRMMORA * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRMULTA      = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMMULTA     
						     ELSE (EVENTOS_TITULOS.VLRMMULTA * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
				EVENTOS_TITULOS.VLRATUMONETARIA,
				EVENTOS_TITULOS.VLRIOF,
				EVENTOS_TITULOS.VLRTARIFA,
				EVENTOS_TITULOS.VLRLANCARCONTA,
				0 QTDEMCOBRANCA,
				0 VLREMCOBRANCA,
				EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
				0 VLRTOTDEBITO, 0 VLRTOTCREDITO,
				@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
				@CIDADE CIDADE , @UF UF, @CEP CEP, PRODUTOS.CODPRODUTOCTB, 
				PRODUTOS.CODESPECIECB,

				@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
				EVENTOS.NOME NOMEEVENTO, /* 02/07/2018 - Fernanda */
				TIPOS_DE_BAIXA.NOME NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
		FROM  EVENTOS_TITULOS
		/*03/07/2018 - Fernanda*/
			JOIN TITULOS   ON EVENTOS_TITULOS.CODCOLIGADA = TITULOS.CODCOLIGADA    
				AND EVENTOS_TITULOS.CODAGENCIA =  TITULOS.CODAGENCIA     
				AND EVENTOS_TITULOS.NUMCARTEIRA = TITULOS.NUMCARTEIRA    
				AND EVENTOS_TITULOS.NOSSONUMERO = TITULOS.NOSSONUMERO
			JOIN OPERACOES ON EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA
				AND EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   
				AND EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO
			JOIN PRODUTOS  ON OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO
			JOIN EVENTOS   ON EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO
			 LEFT OUTER JOIN INFO_INDICES ON TITULOS.CODINDICE = INFO_INDICES.CODINDICE AND
			INFO_INDICES.DATAVIGENCIA   = @DATAPOSICAO	 
			LEFT JOIN TIPOS_DE_BAIXA ON TIPOS_DE_BAIXA.CODBAIXA = EVENTOS_TITULOS.CODBAIXA
			
		WHERE 
			EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
			EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
			EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
			EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
			--EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
			--EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
			--EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
			--OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO    AND	
			OPERACOES.CODPRODUTO        = @P_CODPRODUTO          AND	
			OPERACOES.CODCLIENTE        = @P_CODCLIENTE          AND	
			--EVENTOS_TITULOS.CODCOLIGADA = TITULOS.CODCOLIGADA    AND
			--EVENTOS_TITULOS.CODAGENCIA =  TITULOS.CODAGENCIA     AND
			--EVENTOS_TITULOS.NUMCARTEIRA = TITULOS.NUMCARTEIRA    AND
			--EVENTOS_TITULOS.NOSSONUMERO = TITULOS.NOSSONUMERO    AND
			--EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
			EVENTOS.GERAEXTRATO 	    = 'SIM' 	
			/*03/07/2018 - Fernanda*/	     
UNION
/* Saldo de cada uma das operacoes movimentadas na data */
		SELECT 
			EVENTOS_TITULOS.CODAGENCIA,
			@NOMECLIENTE NOMECLIENTE,
			EVENTOS_TITULOS.DATACADASTRAMENTO,
			PRODUTOS.NOME NOMEPRODUTO,  
			EVENTOS_TITULOS.NUMOPERACAO NUMOPERACAO,	/* 26/10/2010 */
			3 TIPOREGISTRO /* Saldo da Operacao */, 
			NULL SEUNUMERO,
		 	NULL NOMESACADO,
			NULL NOSSONUMERO,
			NULL CODEVENTO,
			NULL SEQEVENTO,
			NULL CODBAIXA,
			NULL CLASSEEVENTO,
			NULL TIPOMOVTOSALDO,
			NULL TIPOMOVTOQTDE,
			NULL DATAVENCIMENTO,
			NULL DATAREFERENCIA,
			NULL DATACONTABILLANCAR,
			0 VLRTITULO,
		      0 VLRDESCONTOS,
		      0 VLRABATIMENTO,
		      0 VLRENCARGOS,
		      0 VLRMORA,
		      0 VLRMULTA,
			0 VLRATUMONETARIA,
			0 VLRIOF,
			0 VLRTARIFA,
			0 VLRLANCARCONTA,
			SALDOS.QTDEMCOBRANCA,SALDOS.VLREMCOBRANCA,
			NULL CODAGENCIALANCAR, NULL NUMCONTALANCAR, 
			0 VLRTOTDEBITO, 0 VLRTOTCREDITO,
			@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
			@CIDADE CIDADE , @UF UF, @CEP CEP, PRODUTOS.CODPRODUTOCTB, NULL CODESPECIECB,
			@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
			NULL NOMEEVENTO, /* 02/07/2018 - Fernanda */
			NULL NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
           FROM  EVENTOS_TITULOS INNER JOIN OPERACOES ON
		EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
		EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
		EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  
	      LEFT OUTER JOIN SALDOS ON
		OPERACOES.CODCOLIGADA      		= SALDOS.CODCOLIGADA     AND
		OPERACOES.CODAGENCIA       		= SALDOS.CODAGENCIA      AND
		OPERACOES.NUMOPERACAO      		= SALDOS.NUMOPERACAO     AND
	        EVENTOS_TITULOS.DATACADASTRAMENTO 	= SALDOS.DATACADASTRAMENTO 	      
	, EVENTOS,  PRODUTOS
	WHERE 
		EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
		EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
		EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
		EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND

		OPERACOES.CODPRODUTO	    = PRODUTOS.CODPRODUTO    AND
		OPERACOES.CODPRODUTO        = @P_CODPRODUTO          AND	
		OPERACOES.CODCLIENTE        = @P_CODCLIENTE          AND	
		EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
		EVENTOS.GERAEXTRATO 	    = 'SIM' 

      GROUP BY EVENTOS_TITULOS.CODAGENCIA, EVENTOS_TITULOS.DATACADASTRAMENTO,PRODUTOS.NOME,
		   EVENTOS_TITULOS.NUMOPERACAO,	SALDOS.QTDEMCOBRANCA,SALDOS.VLREMCOBRANCA,
               PRODUTOS.CODPRODUTOCTB
UNION
/* resumo em conta */
			SELECT 
			EVENTOS_TITULOS.CODAGENCIA,@NOMECLIENTE NOMECLIENTE,
			EVENTOS_TITULOS.DATACADASTRAMENTO, 
			SUBSTRING (#TEMP_FRANCESA.CHAVE, 1, 35) NOMEPRODUTO, /* 26/10/2010 */
			SUBSTRING (#TEMP_FRANCESA.CHAVE, 36, 7) NUMOPERACAO, /* 26/10/2010 */
			2 TIPOREGISTRO,NULL SEUNUMERO,NULL NOMESACADO,NULL NOSSONUMERO,
			NULL CODEVENTO,NULL SEQEVENTO,NULL CODBAIXA,NULL CLASSEEVENTO,
			NULL TIPOMOVTOSALDO,NULL TIPOMOVTOQTDE,NULL DATAVENCIMENTO,
			NULL DATAREFERENCIA,EVENTOS_TITULOS.DATACONTABILLANCAR,0 VLRTITULO,
			0 VLRDESCONTOS,0 VLRABATIMENTO,0 VLRENCARGOS,0 VLRMORA,0 VLRMULTA,
			0 VLRATUMONETARIA,0 VLRIOF,0 VLRTARIFA,0 VLRLANCARCONTA,
			0 QTDEMCOBRANCA, 0 VLREMCOBRANCA,
			EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
                 	SUM (CASE  WHEN EVENTOS_TITULOS.VLRLANCARCONTA <= 0
				     THEN EVENTOS_TITULOS.VLRLANCARCONTA
				     ELSE 0
                       END) VLRTOTDEBITO, 
                 	SUM (CASE  WHEN EVENTOS_TITULOS.VLRLANCARCONTA >= 0
				     THEN EVENTOS_TITULOS.VLRLANCARCONTA
				     ELSE 0
                       END) VLRTOTCREDITO,
			@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
			@CIDADE CIDADE , @UF UF, @CEP CEP, NULL CODPRODUTOCTB, NULL CODESPECIECB,
			@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
			NULL NOMEEVENTO, /* 02/07/2018 - Fernanda */
			NULL NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
		FROM  EVENTOS_TITULOS, EVENTOS, OPERACOES, #TEMP_FRANCESA
		WHERE 
			EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
			EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
			EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
			EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
			EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
			EVENTOS.GERAEXTRATO 	    = 'SIM' 		     AND
			EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
			EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
			EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
			OPERACOES.CODCLIENTE        = @P_CODCLIENTE          AND	
			OPERACOES.CODPRODUTO        = @P_CODPRODUTO	     AND
                  EVENTOS_TITULOS.DATACADASTRAMENTO = #TEMP_FRANCESA.DATACADASTRAMENTO AND
			OPERACOES.CODAGENCIA        = #TEMP_FRANCESA.CODAGENCIA AND
			OPERACOES.CODCLIENTE        = #TEMP_FRANCESA.CODCLIENTE
		GROUP BY   EVENTOS_TITULOS.CODAGENCIA,
			   EVENTOS_TITULOS.DATACADASTRAMENTO, 
			   SUBSTRING (#TEMP_FRANCESA.CHAVE, 1, 35), /* 26/10/2010 */
			   SUBSTRING (#TEMP_FRANCESA.CHAVE, 36, 7), /* 26/10/2010 */
                           EVENTOS_TITULOS.CODAGENCIALANCAR, 
			   EVENTOS_TITULOS.NUMCONTALANCAR, 
			   EVENTOS_TITULOS.DATACONTABILLANCAR

		ORDER BY EVENTOS_TITULOS.DATACADASTRAMENTO, NUMOPERACAO /* 26/10/2010 */, TIPOREGISTRO,  TITULOS.SEUNUMERO
			   END
      END /* emissao liberada */
		   END
		ELSE
/* cliente informado / agencia informada / produto nao informado*/
		   BEGIN
/* Alimentar a tabela auxiliar com a maior operacao movimentada do cliente em cada dia ...*/
			   
			   
			      BEGIN   /* emissao liberada */

			        INSERT INTO #TEMP_FRANCESA
				  (CODAGENCIA, CODCLIENTE, DATACADASTRAMENTO, CHAVE,  /* Eliane - 23/03/2005 */
                		   CODUSUARIOMANUTENCAO, DATAMANUTENCAO)	      /* Eliane - 23/03/2005 */
			          SELECT @P_CODAGENCIA, @P_CODCLIENTE, EVENTOS_TITULOS.DATACADASTRAMENTO,
                                         MAX((PRODUTOS.NOME + REPLICATE ( ' ', (35 - DATALENGTH (PRODUTOS.NOME))) ) + EVENTOS_TITULOS.NUMOPERACAO), /* 26/10/2010 */
			                 @P_CODUSUARIO, GETDATE ()
			          FROM EVENTOS_TITULOS, OPERACOES, PRODUTOS, EVENTOS
			          WHERE
					EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
					EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
					EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
					EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
					EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
					EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
					EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
					OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO    AND	
					OPERACOES.CODCLIENTE        = @P_CODCLIENTE          AND			
					EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
					EVENTOS.GERAEXTRATO 	    = 'SIM' 		     		
			    GROUP BY EVENTOS_TITULOS.DATACADASTRAMENTO
/* movimentacao geral */
				SELECT 
				EVENTOS_TITULOS.CODAGENCIA,
				@NOMECLIENTE NOMECLIENTE,
				EVENTOS_TITULOS.DATACADASTRAMENTO,
				PRODUTOS.NOME NOMEPRODUTO,  
				EVENTOS_TITULOS.NUMOPERACAO NUMOPERACAO /* 26/10/2010 */,
				1 TIPOREGISTRO /* Detalhe */, 
				TITULOS.SEUNUMERO,
			 	SUBSTRING (TITULOS.NOME,1,20) NOMESACADO,
				(EVENTOS_TITULOS.NUMCARTEIRA + '/' + EVENTOS_TITULOS.NOSSONUMERO) NOSSONUMERO,
				EVENTOS_TITULOS.CODEVENTO,
				EVENTOS_TITULOS.SEQEVENTO,
				EVENTOS_TITULOS.CODBAIXA,
				EVENTOS.CLASSEEVENTO,
				EVENTOS.TIPOMOVTOSALDO,
				EVENTOS.TIPOMOVTOQTDE,
				EVENTOS_TITULOS.DATAVENCIMENTO,
				EVENTOS_TITULOS.DATAREFERENCIA,
				EVENTOS_TITULOS.DATACONTABILLANCAR,
				EVENTOS_TITULOS.VLRREGCONTABIL VLRTITULO,
			      VLRDESCONTOS = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMDESCONTOS
						     ELSE (EVENTOS_TITULOS.VLRMDESCONTOS * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRABATIMENTO = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMABATIMENTO
						     ELSE (EVENTOS_TITULOS.VLRMABATIMENTO * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRENCARGOS   = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMENCARGOS  
						     ELSE (EVENTOS_TITULOS.VLRMENCARGOS * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRMORA       = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMMORA      
						     ELSE (EVENTOS_TITULOS.VLRMMORA * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
			      VLRMULTA      = CONVERT(NUMERIC(15,2),
				      	CASE WHEN TITULOS.CODINDICE IS NULL
				 		     THEN EVENTOS_TITULOS.VLRMMULTA     
						     ELSE (EVENTOS_TITULOS.VLRMMULTA * 
							    ISNULL(INFO_INDICES.VALOR,0))
						END /10),
				EVENTOS_TITULOS.VLRATUMONETARIA,
				EVENTOS_TITULOS.VLRIOF,
				EVENTOS_TITULOS.VLRTARIFA,
				EVENTOS_TITULOS.VLRLANCARCONTA,
				0 QTDEMCOBRANCA,
				0 VLREMCOBRANCA,
				EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
				0 VLRTOTDEBITO, 0 VLRTOTCREDITO,
				@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
				@CIDADE CIDADE , @UF UF, @CEP CEP, PRODUTOS.CODPRODUTOCTB, 
				PRODUTOS.CODESPECIECB,
				@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
				EVENTOS.NOME NOMEEVENTO, /* 02/07/2018 - Fernanda */
				TIPOS_DE_BAIXA.NOME NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
		FROM  EVENTOS_TITULOS
		/*03/07/2018 - Fernanda*/
		JOIN TITULOS   ON EVENTOS_TITULOS.CODCOLIGADA = TITULOS.CODCOLIGADA    AND
						  EVENTOS_TITULOS.CODAGENCIA  =  TITULOS.CODAGENCIA    AND
						  EVENTOS_TITULOS.NUMCARTEIRA = TITULOS.NUMCARTEIRA    AND
						  EVENTOS_TITULOS.NOSSONUMERO = TITULOS.NOSSONUMERO
		JOIN OPERACOES ON EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
						  EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
						  EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO
		JOIN PRODUTOS  ON OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO
		JOIN EVENTOS   ON EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO
	    LEFT OUTER JOIN INFO_INDICES ON	TITULOS.CODINDICE = INFO_INDICES.CODINDICE AND
										INFO_INDICES.DATAVIGENCIA   = @DATAPOSICAO	     
		LEFT OUTER JOIN TIPOS_DE_BAIXA ON TIPOS_DE_BAIXA.CODBAIXA = EVENTOS_TITULOS.CODBAIXA
		WHERE 
			EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
			EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
			EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
			EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
			--EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
			--EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
			--EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
			--OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO    AND	
			OPERACOES.CODCLIENTE        = @P_CODCLIENTE          AND	
			--EVENTOS_TITULOS.CODCOLIGADA = TITULOS.CODCOLIGADA    AND
			--EVENTOS_TITULOS.CODAGENCIA =  TITULOS.CODAGENCIA     AND
			--EVENTOS_TITULOS.NUMCARTEIRA = TITULOS.NUMCARTEIRA    AND
			--EVENTOS_TITULOS.NOSSONUMERO = TITULOS.NOSSONUMERO    AND
			--EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
			EVENTOS.GERAEXTRATO 	    = 'SIM' 		     
			/*03/07/2018 - Fernanda*/
UNION
/* Saldo da operacao movimentada na data */
		SELECT 
			EVENTOS_TITULOS.CODAGENCIA,
			@NOMECLIENTE NOMECLIENTE,
			EVENTOS_TITULOS.DATACADASTRAMENTO,
			PRODUTOS.NOME NOMEPRODUTO,  
			EVENTOS_TITULOS.NUMOPERACAO NUMOPERACAO /* 26/10/2010 */,
			3 TIPOREGISTRO /* Saldo da Operacao */, 
			NULL SEUNUMERO,
		 	NULL NOMESACADO,
			NULL NOSSONUMERO,
			NULL CODEVENTO,
			NULL SEQEVENTO,
			NULL CODBAIXA,
			NULL CLASSEEVENTO,
			NULL TIPOMOVTOSALDO,
			NULL TIPOMOVTOQTDE,
			NULL DATAVENCIMENTO,
			NULL DATAREFERENCIA,
			NULL DATACONTABILLANCAR,
			0 VLRTITULO,
		      0 VLRDESCONTOS,
		      0 VLRABATIMENTO,
		      0 VLRENCARGOS,
		      0 VLRMORA,
		      0 VLRMULTA,
			0 VLRATUMONETARIA,
			0 VLRIOF,
			0 VLRTARIFA,
			0 VLRLANCARCONTA,
			SALDOS.QTDEMCOBRANCA,SALDOS.VLREMCOBRANCA,
			NULL CODAGENCIALANCAR, NULL NUMCONTALANCAR, 
			0 VLRTOTDEBITO, 0 VLRTOTCREDITO,
			@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
			@CIDADE CIDADE , @UF UF, @CEP CEP, PRODUTOS.CODPRODUTOCTB, NULL CODESPECIECB,
			@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
			NULL NOMEEVENTO, /* 02/07/2018 - Fernanda */
			NULL NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
	FROM  EVENTOS_TITULOS INNER JOIN OPERACOES ON
		EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
		EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
		EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  
	      LEFT OUTER JOIN SALDOS ON
		OPERACOES.CODCOLIGADA      		= SALDOS.CODCOLIGADA     AND
		OPERACOES.CODAGENCIA       		= SALDOS.CODAGENCIA      AND
		OPERACOES.NUMOPERACAO      		= SALDOS.NUMOPERACAO     AND
	      EVENTOS_TITULOS.DATACADASTRAMENTO 	= SALDOS.DATACADASTRAMENTO	      
	, EVENTOS, PRODUTOS
	WHERE 
		EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
		EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
		EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
		EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND

		OPERACOES.CODPRODUTO	    = PRODUTOS.CODPRODUTO    AND
		OPERACOES.CODCLIENTE        = @P_CODCLIENTE          AND	
		EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
		EVENTOS.GERAEXTRATO 	    = 'SIM' 
 
      GROUP BY EVENTOS_TITULOS.CODAGENCIA, EVENTOS_TITULOS.DATACADASTRAMENTO,PRODUTOS.NOME,
		   EVENTOS_TITULOS.NUMOPERACAO,	SALDOS.QTDEMCOBRANCA,SALDOS.VLREMCOBRANCA,
               PRODUTOS.CODPRODUTOCTB
UNION
/* resumo em conta */
			SELECT 
			EVENTOS_TITULOS.CODAGENCIA,@NOMECLIENTE NOMECLIENTE,
			EVENTOS_TITULOS.DATACADASTRAMENTO, 
			SUBSTRING (#TEMP_FRANCESA.CHAVE, 1, 35) NOMEPRODUTO, /* 26/10/2010 */
			SUBSTRING (#TEMP_FRANCESA.CHAVE, 36, 7) NUMOPERACAO  /* 26/10/2010 */, 
			2 TIPOREGISTRO, 
			NULL SEUNUMERO,NULL NOMESACADO,NULL NOSSONUMERO,
			NULL CODEVENTO,NULL SEQEVENTO,NULL CODBAIXA,NULL CLASSEEVENTO,
			NULL TIPOMOVTOSALDO,NULL TIPOMOVTOQTDE,NULL DATAVENCIMENTO,
			NULL DATAREFERENCIA,EVENTOS_TITULOS.DATACONTABILLANCAR,0 VLRTITULO,
			0 VLRDESCONTOS,0 VLRABATIMENTO,0 VLRENCARGOS,0 VLRMORA,0 VLRMULTA,
			0 VLRATUMONETARIA,0 VLRIOF,0 VLRTARIFA,0 VLRLANCARCONTA,
			0 QTDEMCOBRANCA, 0 VLREMCOBRANCA,
			EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
                 	SUM (CASE  WHEN EVENTOS_TITULOS.VLRLANCARCONTA <= 0
				     THEN EVENTOS_TITULOS.VLRLANCARCONTA
				     ELSE 0
                       END) VLRTOTDEBITO, 
                 	SUM (CASE  WHEN EVENTOS_TITULOS.VLRLANCARCONTA >= 0
				     THEN EVENTOS_TITULOS.VLRLANCARCONTA
				     ELSE 0
                       END) VLRTOTCREDITO,
			@ENDERECO ENDERECO, @COMPLEMENTO COMPLEMENTO, @BAIRRO BAIRRO,
			@CIDADE CIDADE , @UF UF, @CEP CEP, NULL CODPRODUTOCTB, NULL CODESPECIECB,
			@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
			NULL NOMEEVENTO, /* 02/07/2018 - Fernanda */
			NULL NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
		FROM  EVENTOS_TITULOS, EVENTOS, OPERACOES, #TEMP_FRANCESA
		WHERE 
			EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
			EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
			EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
			EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
			EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
			EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
			EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
			OPERACOES.CODCLIENTE        = @P_CODCLIENTE          AND	
			EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
			EVENTOS.GERAEXTRATO 	    = 'SIM' 		     AND
                  EVENTOS_TITULOS.DATACADASTRAMENTO = #TEMP_FRANCESA.DATACADASTRAMENTO AND
			OPERACOES.CODAGENCIA        = #TEMP_FRANCESA.CODAGENCIA AND
			OPERACOES.CODCLIENTE        = #TEMP_FRANCESA.CODCLIENTE
		GROUP BY EVENTOS_TITULOS.CODAGENCIA,
			   EVENTOS_TITULOS.DATACADASTRAMENTO, 
			   SUBSTRING (#TEMP_FRANCESA.CHAVE, 1, 35), /* 26/10/2010 */
			   SUBSTRING (#TEMP_FRANCESA.CHAVE, 36, 7 ) /* 26/10/2010 */, 
			   EVENTOS_TITULOS.CODAGENCIALANCAR, 
			   EVENTOS_TITULOS.NUMCONTALANCAR, EVENTOS_TITULOS.DATACONTABILLANCAR

		ORDER BY EVENTOS_TITULOS.DATACADASTRAMENTO, NOMEPRODUTO, NUMOPERACAO /* 26/10/2010 */,TIPOREGISTRO, TITULOS.SEUNUMERO
			      END    /* emissao liberada */
		   END
	   END
   END
   
/* AQUI TESTADO */
   
ELSE
/* cliente nao informado, pegar todo o movto da agencia */
   BEGIN
/* Alimentar a tabela auxiliar com a maior operacao movimentada do cliente em cada dia ...*/
      BEGIN   /* emissao liberada */

        INSERT INTO #TEMP_FRANCESA
	  (CODAGENCIA, CODCLIENTE, DATACADASTRAMENTO, CHAVE,  /* Eliane - 23/03/2005 */
           CODUSUARIOMANUTENCAO, DATAMANUTENCAO)	      /* Eliane - 23/03/2005 */
          SELECT @P_CODAGENCIA, OPERACOES.CODCLIENTE, EVENTOS_TITULOS.DATACADASTRAMENTO,
                 MAX((PRODUTOS.NOME + REPLICATE ( ' ', (35 - DATALENGTH (PRODUTOS.NOME))) ) + EVENTOS_TITULOS.NUMOPERACAO), /* 26/10/2010 */
                 @P_CODUSUARIO, GETDATE ()
          FROM EVENTOS_TITULOS, OPERACOES, PRODUTOS, EVENTOS
          WHERE
		EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
		EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
		EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
		EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
		EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
		EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
		EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
		OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO    AND	
		EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
		EVENTOS.GERAEXTRATO 	    = 'SIM' 		     		
	GROUP BY EVENTOS_TITULOS.DATACADASTRAMENTO, OPERACOES.CODCLIENTE
/* movimentacao geral */
	SELECT 
	EVENTOS_TITULOS.CODAGENCIA,
	ISNULL (INFO_CLIENTES.NOME, OPERACOES.CODCLIENTE + ' CLIENTE NAO CADASTRADO NO INFOBANK') NOMECLIENTE,
	EVENTOS_TITULOS.DATACADASTRAMENTO,
	PRODUTOS.NOME NOMEPRODUTO,  
	EVENTOS_TITULOS.NUMOPERACAO NUMOPERACAO,	/* 26/10/2010 */
	1 TIPOREGISTRO /* Detalhe */, 
	TITULOS.SEUNUMERO,
 	SUBSTRING (TITULOS.NOME,1,20) NOMESACADO,
	(EVENTOS_TITULOS.NUMCARTEIRA + '/' + EVENTOS_TITULOS.NOSSONUMERO) NOSSONUMERO,
	EVENTOS_TITULOS.CODEVENTO,
	EVENTOS_TITULOS.SEQEVENTO,
	EVENTOS_TITULOS.CODBAIXA,
	EVENTOS.CLASSEEVENTO,
	EVENTOS.TIPOMOVTOSALDO,
	EVENTOS.TIPOMOVTOQTDE,
	EVENTOS_TITULOS.DATAVENCIMENTO,
	EVENTOS_TITULOS.DATAREFERENCIA,
	EVENTOS_TITULOS.DATACONTABILLANCAR,
	EVENTOS_TITULOS.VLRREGCONTABIL VLRTITULO,
      VLRDESCONTOS = CONVERT(NUMERIC(15,2),
	      	CASE WHEN TITULOS.CODINDICE IS NULL
	 		     THEN EVENTOS_TITULOS.VLRMDESCONTOS
			     ELSE (EVENTOS_TITULOS.VLRMDESCONTOS * 
				    ISNULL(INFO_INDICES.VALOR,0))
			END /10),
      VLRABATIMENTO = CONVERT(NUMERIC(15,2),
	      	CASE WHEN TITULOS.CODINDICE IS NULL
	 		     THEN EVENTOS_TITULOS.VLRMABATIMENTO
			     ELSE (EVENTOS_TITULOS.VLRMABATIMENTO * 
				    ISNULL(INFO_INDICES.VALOR,0))
			END /10),
     VLRENCARGOS   = CONVERT(NUMERIC(15,2),
	      	CASE WHEN TITULOS.CODINDICE IS NULL
	 		     THEN EVENTOS_TITULOS.VLRMENCARGOS  
			     ELSE (EVENTOS_TITULOS.VLRMENCARGOS * 
				    ISNULL(INFO_INDICES.VALOR,0))
			END /10),
      VLRMORA       = CONVERT(NUMERIC(15,2),
	      	CASE WHEN TITULOS.CODINDICE IS NULL
	 		     THEN EVENTOS_TITULOS.VLRMMORA      
			     ELSE (EVENTOS_TITULOS.VLRMMORA * 
				    ISNULL(INFO_INDICES.VALOR,0))
			END /10),
      VLRMULTA      = CONVERT(NUMERIC(15,2),
	      	CASE WHEN TITULOS.CODINDICE IS NULL
	 		     THEN EVENTOS_TITULOS.VLRMMULTA     
			     ELSE (EVENTOS_TITULOS.VLRMMULTA * 
				    ISNULL(INFO_INDICES.VALOR,0))
			END /10),
	EVENTOS_TITULOS.VLRATUMONETARIA,
	EVENTOS_TITULOS.VLRIOF,
	EVENTOS_TITULOS.VLRTARIFA,
	EVENTOS_TITULOS.VLRLANCARCONTA,
	0 QTDEMCOBRANCA,
	0 VLREMCOBRANCA,
	EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
	0 VLRTOTDEBITO, 0 VLRTOTCREDITO,
	INFO_CLIENTE_ENDERECOS.ENDERECO ENDERECO, INFO_CLIENTE_ENDERECOS.COMPLEMENTO COMPLEMENTO, 
	INFO_CLIENTE_ENDERECOS.BAIRRO BAIRRO, INFO_CLIENTE_ENDERECOS.CIDADE CIDADE, 
	INFO_CLIENTE_ENDERECOS.UF UF, INFO_CLIENTE_ENDERECOS.CEP CEP, PRODUTOS.CODPRODUTOCTB,
	PRODUTOS.CODESPECIECB,
	@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
	EVENTOS.NOME NOMEEVENTO, /* 02/07/2018 - Fernanda */
	TIPOS_DE_BAIXA.NOME NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
	FROM  EVENTOS_TITULOS
      JOIN TITULOS ON EVENTOS_TITULOS.CODCOLIGADA = TITULOS.CODCOLIGADA    AND
                      EVENTOS_TITULOS.CODAGENCIA =  TITULOS.CODAGENCIA     AND
                      EVENTOS_TITULOS.NUMCARTEIRA = TITULOS.NUMCARTEIRA    AND
                      EVENTOS_TITULOS.NOSSONUMERO = TITULOS.NOSSONUMERO    
      JOIN OPERACOES ON EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
                        EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
                        EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO 
      JOIN PRODUTOS ON OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO   
		JOIN EVENTOS ON EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO  
      JOIN INFO_CLIENTES ON OPERACOES.CODCLIENTE        = INFO_CLIENTES.CODCLIENTE
      LEFT OUTER JOIN INFO_INDICES ON TITULOS.CODINDICE          = INFO_INDICES.CODINDICE AND
                                      INFO_INDICES.DATAVIGENCIA   = @DATAPOSICAO		
      LEFT OUTER JOIN INFO_CLIENTE_ENDERECOS ON INFO_CLIENTE_ENDERECOS.CGC_CPF   = INFO_CLIENTES.CGC_CPF AND
		                                          INFO_CLIENTE_ENDERECOS.SEQUENCIA = INFO_CLIENTES.SEQUENCIA 		
		LEFT OUTER JOIN TIPOS_DE_BAIXA ON TIPOS_DE_BAIXA.CODBAIXA = EVENTOS_TITULOS.CODBAIXA
	WHERE 
		EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
		EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
		EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
		EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
		--EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
		--EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
		--EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
		--OPERACOES.CODCLIENTE        = INFO_CLIENTES.CODCLIENTE AND

		--OPERACOES.CODPRODUTO        = PRODUTOS.CODPRODUTO    AND	
		--EVENTOS_TITULOS.CODCOLIGADA = TITULOS.CODCOLIGADA    AND
		--EVENTOS_TITULOS.CODAGENCIA =  TITULOS.CODAGENCIA     AND
		--EVENTOS_TITULOS.NUMCARTEIRA = TITULOS.NUMCARTEIRA    AND
		--EVENTOS_TITULOS.NOSSONUMERO = TITULOS.NOSSONUMERO    AND
		--EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
		EVENTOS.GERAEXTRATO 	    = 'SIM' 		     
	     
UNION
/* Saldo da operacao movimentada na data */
		SELECT 
			EVENTOS_TITULOS.CODAGENCIA,
			ISNULL (INFO_CLIENTES.NOME, OPERACOES.CODCLIENTE + ' CLIENTE NAO CADASTRADO NO INFOBANK') NOMECLIENTE,
			EVENTOS_TITULOS.DATACADASTRAMENTO,
			PRODUTOS.NOME NOMEPRODUTO,  
			EVENTOS_TITULOS.NUMOPERACAO NUMOPERACAO,	/* 26/10/2010 */
			3 TIPOREGISTRO /* Saldo de Operacao */, 
			NULL SEUNUMERO,
		 	NULL NOMESACADO,
			NULL NOSSONUMERO,
			NULL CODEVENTO,
			NULL SEQEVENTO,
			NULL CODBAIXA,
			NULL CLASSEEVENTO,
			NULL TIPOMOVTOSALDO,
			NULL TIPOMOVTOQTDE,
			NULL DATAVENCIMENTO,
			NULL DATAREFERENCIA,
			NULL DATACONTABILLANCAR,
			0 VLRTITULO,
		      0 VLRDESCONTOS,
		      0 VLRABATIMENTO,
		      0 VLRENCARGOS,
		      0 VLRMORA,
		      0 VLRMULTA,
			0 VLRATUMONETARIA,
			0 VLRIOF,
			0 VLRTARIFA,
			0 VLRLANCARCONTA,
			SALDOS.QTDEMCOBRANCA, SALDOS.VLREMCOBRANCA,
			NULL CODAGENCIALANCAR, NULL NUMCONTALANCAR, 
			0 VLRTOTDEBITO, 0 VLRTOTCREDITO,
			INFO_CLIENTE_ENDERECOS.ENDERECO ENDERECO, INFO_CLIENTE_ENDERECOS.COMPLEMENTO COMPLEMENTO, 
			INFO_CLIENTE_ENDERECOS.BAIRRO BAIRRO, INFO_CLIENTE_ENDERECOS.CIDADE CIDADE, 
			INFO_CLIENTE_ENDERECOS.UF UF, INFO_CLIENTE_ENDERECOS.CEP CEP, 
			PRODUTOS.CODPRODUTOCTB, NULL CODESPECIECB,
			@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
			NULL NOMEEVENTO, /* 02/07/2018 - Fernanda */
			NULL NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
	FROM   EVENTOS,  PRODUTOS, 
	       INFO_CLIENTES LEFT OUTER JOIN INFO_CLIENTE_ENDERECOS ON
		INFO_CLIENTE_ENDERECOS.CGC_CPF   = INFO_CLIENTES.CGC_CPF   AND
		INFO_CLIENTE_ENDERECOS.SEQUENCIA = INFO_CLIENTES.SEQUENCIA 
	      , EVENTOS_TITULOS INNER JOIN OPERACOES ON
		EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  		AND
		EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   		AND
		EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  	      
	         LEFT OUTER JOIN SALDOS ON
		OPERACOES.CODCOLIGADA      		= SALDOS.CODCOLIGADA   AND
		OPERACOES.CODAGENCIA       		= SALDOS.CODAGENCIA    AND
		OPERACOES.NUMOPERACAO      		= SALDOS.NUMOPERACAO   AND
	        EVENTOS_TITULOS.DATACADASTRAMENTO 	= SALDOS.DATACADASTRAMENTO
		
	WHERE 
		EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   		AND
		EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      		AND
		EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         		AND
		EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          		AND

		OPERACOES.CODCLIENTE        = INFO_CLIENTES.CODCLIENTE      AND

		OPERACOES.CODPRODUTO	    = PRODUTOS.CODPRODUTO    		AND
		EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      		AND
		EVENTOS.GERAEXTRATO 	    = 'SIM' 		     		

      GROUP BY EVENTOS_TITULOS.CODAGENCIA, EVENTOS_TITULOS.DATACADASTRAMENTO,INFO_CLIENTES.NOME,
		   PRODUTOS.NOME, OPERACOES.CODCLIENTE,EVENTOS_TITULOS.NUMOPERACAO,	SALDOS.QTDEMCOBRANCA,SALDOS.VLREMCOBRANCA,
		   INFO_CLIENTE_ENDERECOS.ENDERECO, INFO_CLIENTE_ENDERECOS.COMPLEMENTO, 
		   INFO_CLIENTE_ENDERECOS.BAIRRO, INFO_CLIENTE_ENDERECOS.CIDADE, 
		   INFO_CLIENTE_ENDERECOS.UF, INFO_CLIENTE_ENDERECOS.CEP, PRODUTOS.CODPRODUTOCTB
UNION
/* resumo em conta */
			SELECT 
			EVENTOS_TITULOS.CODAGENCIA,
			ISNULL (INFO_CLIENTES.NOME, OPERACOES.CODCLIENTE + ' CLIENTE NAO CADASTRADO NO INFOBANK') NOMECLIENTE,
			EVENTOS_TITULOS.DATACADASTRAMENTO, 
			SUBSTRING (#TEMP_FRANCESA.CHAVE, 1, 35) NOMEPRODUTO, /* 26/10/2010 */
			SUBSTRING (#TEMP_FRANCESA.CHAVE, 36, 7) NUMOPERACAO, /* 26/10/2010 */
			2 TIPOREGISTRO,NULL SEUNUMERO,NULL NOMESACADO,NULL NOSSONUMERO,
			NULL CODEVENTO,NULL SEQEVENTO,NULL CODBAIXA,NULL CLASSEEVENTO,
			NULL TIPOMOVTOSALDO,NULL TIPOMOVTOQTDE,NULL DATAVENCIMENTO,
			NULL DATAREFERENCIA,EVENTOS_TITULOS.DATACONTABILLANCAR,0 VLRTITULO,
			0 VLRDESCONTOS,0 VLRABATIMENTO,0 VLRENCARGOS,0 VLRMORA,0 VLRMULTA,
			0 VLRATUMONETARIA,0 VLRIOF,0 VLRTARIFA,0 VLRLANCARCONTA,
			0 QTDEMCOBRANCA, 0 VLREMCOBRANCA,
			EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
                 	SUM (CASE  WHEN EVENTOS_TITULOS.VLRLANCARCONTA <= 0
				     THEN EVENTOS_TITULOS.VLRLANCARCONTA
				     ELSE 0
                       END) VLRTOTDEBITO, 
                 	SUM (CASE  WHEN EVENTOS_TITULOS.VLRLANCARCONTA >= 0
				     THEN EVENTOS_TITULOS.VLRLANCARCONTA
				     ELSE 0
                       END) VLRTOTCREDITO,
			NULL ENDERECO, NULL COMPLEMENTO, NULL BAIRRO, NULL CIDADE, NULL UF, NULL CEP, 
			NULL CODPRODUTOCTB, NULL CODESPECIECB,
			@CODNOSSOBANCO CODBANCO, /* 24/01/2012 - Eliane */
			NULL NOMEEVENTO, /* 02/07/2018 - Fernanda */
			NULL NOMETIPOBAIXA /* 02/07/2018 - Fernanda */
		FROM  EVENTOS_TITULOS, EVENTOS,OPERACOES, INFO_CLIENTES, #TEMP_FRANCESA
		WHERE 
			EVENTOS_TITULOS.DATACADASTRAMENTO >= @P_DATAINICIO   AND
			EVENTOS_TITULOS.DATACADASTRAMENTO <= @P_DATAFIM      AND
			EVENTOS_TITULOS.CODCOLIGADA = @P_CODCOLIGADA         AND
			EVENTOS_TITULOS.CODAGENCIA  = @P_CODAGENCIA          AND
			EVENTOS_TITULOS.CODEVENTO   = EVENTOS.CODEVENTO      AND
			EVENTOS.GERAEXTRATO 	    = 'SIM' 		     AND
			EVENTOS_TITULOS.CODCOLIGADA = OPERACOES.CODCOLIGADA  AND
			EVENTOS_TITULOS.CODAGENCIA  = OPERACOES.CODAGENCIA   AND
			EVENTOS_TITULOS.NUMOPERACAO = OPERACOES.NUMOPERACAO  AND
			OPERACOES.CODCLIENTE        = INFO_CLIENTES.CODCLIENTE AND
                  EVENTOS_TITULOS.DATACADASTRAMENTO = #TEMP_FRANCESA.DATACADASTRAMENTO AND
			OPERACOES.CODAGENCIA        = #TEMP_FRANCESA.CODAGENCIA AND
			OPERACOES.CODCLIENTE        = #TEMP_FRANCESA.CODCLIENTE

		GROUP BY EVENTOS_TITULOS.CODAGENCIA, 
		 	ISNULL (INFO_CLIENTES.NOME, OPERACOES.CODCLIENTE + ' CLIENTE NAO CADASTRADO NO INFOBANK'),
			   EVENTOS_TITULOS.DATACADASTRAMENTO, 
  			   SUBSTRING (#TEMP_FRANCESA.CHAVE, 1, 35), /* 26/10/2010 */
			   SUBSTRING (#TEMP_FRANCESA.CHAVE, 36, 7), /* 26/10/2010 */
			   EVENTOS_TITULOS.CODAGENCIALANCAR, EVENTOS_TITULOS.NUMCONTALANCAR, 
			   EVENTOS_TITULOS.DATACONTABILLANCAR

		ORDER BY NOMECLIENTE, EVENTOS_TITULOS.DATACADASTRAMENTO,NOMEPRODUTO,
			 NUMOPERACAO, /* 26/10/2010 */ TIPOREGISTRO,TITULOS.SEUNUMERO
     END /* emissao liberada */
   END

TRATAERRO:
   PRINT(@P_MENSERRO)

DROP TABLE #TEMP_FRANCESA

--SELECT * FROM TITULOS WHERE NOSSONUMERO = '00121722468'